### ISSUE TITLE
JWT Authentication Error

### ISSUE THREAD

**Issue by christopher-cox** [Open-MBEE/jupyter-mdk#3]
Hello,

I'm having a difficult time debugging the reason for getting the following error:

Traceback (most recent call last):
  File "/Users/christophercox/opt/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/notebook/notebookapp.py", line 2121, in initialize
    self.init_configurables()
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/notebook/notebookapp.py", line 1661, in init_configurables
    self.contents_manager = self.contents_manager_class(
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/mmscontents/mmsmanager.py", line 28, in __init__
    self._mms_token = get_mms_token(self.mms_url, self.mms_username, self.mms_password)
  File "/Users/christophercox/opt/anaconda3/lib/python3.9/site-packages/mmscontents/service.py", line 45, in get_mms_token
    jwt_authentication_request = mms_client.JwtAuthenticationRequest()
AttributeError: module 'mms_python_client' has no attribute 'JwtAuthenticationRequest'

I'm thinking it's not configured correctly when it runs the get_mms_token request, but I've verified the url, username, and password. I uninstalled PyJWT (2.1.0) and upgraded to 2.3.0, but I still get the same error. Any help on the issue would be appreciated!

I'm running MacOS Monterey, Python 3.9, and Anaconda 2.1.4, but I've also failed when doing the same on Windows with the same (Python 3.9, etc.).

**Comment by christopher-cox** [comment]
After a little bit of searching, it seems like JwtAuthenticationRequest does not exist in current versions of the mms-python-client.
